# Generated by Django 4.1 on 2022-08-17 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_packagepurchasehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepurchasehistory',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.packagename'),
        ),
    ]
