# Generated by Django 3.2 on 2022-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepurchasehistory',
            name='isConfirmationMailSent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
