# Generated by Django 3.2 on 2022-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_packagepurchasehistory_isconfirmationmailsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepurchasehistory',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
