# Generated by Django 3.2.15 on 2022-09-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_perpetualgrowthratedata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perpetualgrowthratedata',
            options={'ordering': ['-pk']},
        ),
    ]
