# Generated by Django 3.2.15 on 2022-09-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_perpetualgrowthratedata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedIntrinsicValueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=255)),
                ('symbol_name', models.CharField(max_length=255)),
                ('symbol_currency', models.CharField(max_length=255)),
                ('revenue_ttm', models.CharField(max_length=255)),
                ('nop_ttm', models.CharField(max_length=255)),
                ('roe', models.CharField(max_length=255)),
                ('roc', models.CharField(max_length=255)),
                ('ke', models.CharField(max_length=255)),
                ('kd', models.CharField(max_length=255)),
                ('ev', models.CharField(max_length=255)),
                ('wacc', models.CharField(max_length=255)),
                ('market_cap', models.CharField(max_length=255)),
                ('stage_1_growth', models.CharField(max_length=255)),
                ('stage_2_growth', models.CharField(max_length=255)),
                ('perpetual_growth_rate', models.CharField(max_length=255)),
                ('de_ratio', models.CharField(max_length=255)),
                ('beta', models.CharField(max_length=255)),
                ('intrinsic_value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
