# Generated by Django 3.2.15 on 2022-09-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_estimatedintrinsicvaluedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedintrinsicvaluedata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
