# Generated by Django 4.1 on 2022-08-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('phone_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_paid_member', models.BooleanField(default=False)),
                ('is_a_staff', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('1', 'Verified'), ('0', 'Not Verified')], default=0, max_length=20, null=True)),
                ('is_agreed_with_termsConsition', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
