# Generated by Django 4.1 on 2022-08-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership_status',
            field=models.CharField(blank=True, choices=[('pro_member', 'Pro-Member'), ('free_member', 'Free')], max_length=255, null=True),
        ),
    ]
