# Generated by Django 4.1 on 2022-08-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='membership_status',
        ),
    ]
