# Generated by Django 3.2 on 2022-08-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
