# Generated by Django 3.2.15 on 2022-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profileimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_free_trial_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
